spring:
  datasource:
    url: jdbc:mariadb://db.newlecture.com:3306/iljodb
    driver-class-name: org.mariadb.jdbc.Driver
    username: iljo
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true
  security:
    jwt:
      token:
        secret: 'Fb24YTIvxPQreBYwnS4KliDx6L53zgur0k2JsQaJxXE753F68B4'
        expire-length: 3600000
    oauth2:
      client:
        registration:
          google:
            client-id: 34817630454-12fm40h4r3ph0s7if8uo9m8oonue0f0h.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: kyb00Xn5N69KHm4aLjRy
            client-secret: h9LqIFdSuS
            client-name: Naver
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-id: 93ddfacb71c42e9da53de1bba2502e36
            client-secret: ttMdYR7QecLpwG1hvTsgEX12Znp4p0CG
            client-name: Kakao
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
mybatis:
  type-aliases-package: com.mechoori.web.entity
  mapper-locations:
  - classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true