spring:
  aop:
    proxy-target-class: true
  # profiles:
  #   include: oauth
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  datasource:
    url: jdbc:mariadb://db.newlecture.com:3306/iljodb
    driver-class-name: org.mariadb.jdbc.Driver
    username: iljo
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order-inserts: true
        order-updates: true
        format-sql: true
        show-sql: true
  security:
  #   jwt:
  #     token:
  #       secret: 'Fb24YTIvxPQreBYwnS4KliDx6L53zgur0k2JsQaJxXE753F68B4'
  #       expire-length: 3600000
    oauth2:
      client:
        registration:
          google:
            client-id: 34817630454-12fm40h4r3ph0s7if8uo9m8oonue0f0h.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: kyb00Xn5N69KHm4aLjRy
            client-secret: h9LqIFdSuS
            client-name: Naver
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-id: 93ddfacb71c42e9da53de1bba2502e36
            client-secret: ttMdYR7QecLpwG1hvTsgEX12Znp4p0CG
            client-name: Kakao
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

upload:
  files: "/images/member/review/"

mybatis:
  type-aliases-package: com.mechoori.web.entity
  mapper-locations:
  - classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

#     # Naver smtp server 사용
# spring:
#   mail:
#     host: smtp.naver.com #smtp 서버 주소
#     port: 465 # 메일 인증서버 포트
#     username: mechoori2023 #네이버 아이디
#     password: testemailapi #네이버 비밀번호
#     properties:
#       mail:
#         smtp:
#           starttls:
#             enable: true
#           #            required: true
#           auth: true
#           #          connectiontimeout: 5000
#           #          timeout: 5000
#           #          writetimeout: 5000
#           ssl:
#             #trust: smtp.naver.com
#             enable: true #반드시 필요 -> SSL 필요로 되어있으면